baseURL: https://sleepingsaint.github.io/blog/ 
languageCode: en-us
title: sleepingsaint
theme: sleepingsaint

taxonomies:
  category: categories
  tag: tags
  series: series

menu:
  main:
    - identifier: posts 
      name: Posts
      url: posts/
    - identifier: series
      name: Series
      url: series/
    - identifier: tags
      name: Tags
      url: tags/

markup:
  goldmark:
    renderer:
      unsafe: true